### ISSUE TITLE
Scan all returns nothing or hangs, android plex app connects fine

### ISSUE THREAD

**Issue by timelf123** [atomjack/VoiceControlForPlex#13]
Tested with PMS host firewall off
Same wifi/subnet

Galaxy S6

**Comment by atomjack** [comment]
I'll need you to attach device logs to this issue if I'm going to track down the problem (I tried it using Scan All just now and it worked fine). Hit the menu button, then email device logs, and email it to yourself, then attach to this issue. Please also make sure you are running the latest version of the app (2.0.5).

**Comment by timelf123** [comment]
Manufacturer: samsung
Device: zerofltetmo
Model: SM-G920T
Product: zerofltetmo
Version: 5.1.1
App Version: 2.0.5

Logged in: no

Description of the issue: can't find local PMS

[vcfp-log.txt](https://files.zenhub.io/5697e7b4b8516b1b4867d58c)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by atomjack** [comment]
I see the following line in the log:

```D/VoiceControlForPlex(15226): Failed to find connection for beastmode2: 401
```
401 is unauthorized, which most likely means your PMS is set to only allow authorized plex accounts to connect. You'll either have to disable that, or login through the app first.

Also, I did find an error that causes the app to crash when trying to play something using Scan All, and will have an apk for you to test in a little while.

Thanks for bringing this to my attention!

**Comment by atomjack** [comment]
Can you give this apk a try? Should fix the Scan All crash.
[VoiceControlForPlex2.0.6b1.apk.zip](https://github.com/atomjack/VoiceControlForPlex/files/90841/VoiceControlForPlex2.0.6b1.apk.zip)

**Comment by timelf123** [comment]
Thanks for the quick response! Logging in fixed it. Still need me to test the APK?

**Comment by atomjack** [comment]
Yeah, if you wouldn't mind. Weren't you getting some crashes when using scan all?

**Comment by timelf123** [comment]
Apologies, I forgot to come back and update you. The scan all fix seemed to work for me :)
